import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";

const playSans = Play({
  subsets: ["latin"],
  variable: "--font-play-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playSans.variable}  antialiased`}>{children}</body>
    </html>
  );
}
